Repository openyurtio/community, pull requests merged in 2022-06, with the labels that each got.

#40 Add sigs info in README and data plane sig repos
  README.md
  sig-list.md
Labels: size/S

#41 update controlplane sig repos
  sig-list.md
Labels: lgtm, size/M

#42 Add IoT SIG
  sig-list.md
Labels: size/XS
